version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ControleCadastro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ControleCadastro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
